---
- name: Provision reverse proxy VM
  hosts: reverse_proxy
  become: true

  roles:
    - base_user
    - pip_packages
    - uptime_kuma
    - nginx_proxy
    - zram
    - wireguard
    - dnf_automatic
    - dnf_kernel_limit
